exclude: ^(docs)$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
        exclude: ^deployment/fluidos-meta-orchestrator/templates/
        args: [ -m ]
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-shebang-scripts-are-executable
    -   id: name-tests-test
        args: [ --pytest-test-first ]
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.15.0
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories, '.:src', --py310-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.16.1'
    hooks:
    -   id: mypy
        args: [
            --exclude, 'fluidos_model_orchestrator/rescheduler/idl/idl_pb2.pyi',
            --follow-untyped-imports,
            --install-types, --non-interactive
        ]
-   repo: https://github.com/PyCQA/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    -   id: yesqa
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
