name: Publish Docker image on FLUIDOS Docker Hub

on:
  push:
    tags: [ 'v*.*.*' ]
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: fluidos/fluidos-metaorchestrator
  IMAGE_BASE_NAME: fluidos-metaorchestrator
  ORG_NAME: fluidos

jobs:
  build:
    runs-on:
        - self-hosted
        - fluidos
        - polito
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fluidos
          password: ${{ secrets.DOCKER_HUB_WRITE_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
          labels: ${{ steps.meta.outputs.labels }}
